type: preprocessor
tune_mode: params
pipeline:
  - type: normalize
    target: Log1P
    params_to_tune:
      base:
        min: 1.0
        max: 10.0
  - type: filter.gene
    target: HighlyVariableGenesLogarithmizedByTopGenes
    params_to_tune:
      n_top_genes:
        min: 100
        max: 2000
      n_bins:
        min: 10
        max: 30
      flavor:
        values:
          - seurat
          - cell_ranger
  - type: feature.cell
    target: WeightedFeaturePCA
    params:
      out: feature.cell
    params_to_tune:
      n_components:
        min: 100
        max: 1000
      feat_norm_mode:
        values:
          - null
          - normalize
          - standardize
          - minmax
          - l2
  - type: graph.cell
    target: CellFeatureGraph
    params:
      cell_feature_channel: feature.cell
  - type: misc
    target: SetConfig
    params:
      config_dict:
        label_channel: cell_type
wandb:
  entity: danceteam
  project: dance-dev
  method: bayes
  metric:
    name: acc
    goal: maximize
