type: preprocessor
tune_mode: params
pipeline:
  - type: normalize
    target: Log1P
    params_to_tune:
      base:
        min: 1.0
        max: 10.0
  - type: filter.gene
    target: FilterGenesPercentile
    params_to_tune:
      min_val:
        min: 1
        max: 10
      max_val:
        min: 95
        max: 99
      mode:
        values:
          - sum
          - var
          - cv
          - rv
  - type: feature.cell
    target: FeatureCellPlaceHolder
    params:
      out: feature.cell
  - type: graph.cell
    target: CellFeatureGraph
    params:
      cell_feature_channel: feature.cell
  - type: misc
    target: SetConfig
    params:
      config_dict:
        label_channel: cell_type
wandb:
  entity: danceteam
  project: dance-dev
  method: bayes
  metric:
    name: acc
    goal: maximize
