type: preprocessor
tune_mode: pipeline
pipeline:
  - type: normalize
    include:
      - ScaleFeature
      - ScTransform
      - Log1P
      - NormalizeTotal
    default_params:
      ScTransform:
        min_cells: 2
        n_genes: 3000
        bin_size: 200
  - type: filter.gene
    include:
      - HighlyVariableGenesLogarithmizedByMeanAndDisp
      - HighlyVariableGenesRawCount
      - HighlyVariableGenesLogarithmizedByTopGenes
      - FilterGenesPercentile
      - FilterGenesTopK
      - FilterGenesRegression
      - FilterGenesScanpyOrder
    default_params:
      FilterGenesScanpyOrder:
        order:
          - min_counts
          - min_cells
          - max_counts
          - max_cells
        min_counts: 1
        max_counts: 5000
        min_cells: 1
        max_cells: 5000
      HighlyVariableGenesLogarithmizedByMeanAndDisp:
        max_mean: 20
        min_disp: 0.1
        min_mean: 0
  - type: misc
    target: SetConfig
    params:
      config_dict:
        label_channel: cell_type
wandb:
  entity: danceteam
  project: dance-dev
  method: grid
  metric:
    name: acc
    goal: maximize
