type: preprocessor
tune_mode: params
pipeline:
  - type: normalize
    target: Log1P
    params_to_tune:
      base:
        min: 1.0
        max: 10.0
  - type: filter.gene
    target: FilterGenesPercentile
    params_to_tune:
      min_val:
        min: 1
        max: 10
      max_val:
        min: 95
        max: 99
      mode:
        values:
          - sum
          - var
          - cv
          - rv
  - type: feature.cell
    target: CellPCA
    params:
      out: feature.cell
    params_to_tune:
      n_components:
        min: 100
        max: 1000
  - type: misc
    target: SetConfig
    params:
      config_dict:
        feature_channel: feature.cell
        label_channel: cell_type
wandb:
  entity: danceteam
  project: dance-dev
  method: bayes
  metric:
    name: acc
    goal: maximize
